#ifndef EXAMPLE1_MODULE_GLOBAL_H
#define EXAMPLE1_MODULE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EXAMPLE1_MODULE_LIBRARY)
#  define EXAMPLE1_MODULESHARED_EXPORT Q_DECL_EXPORT
#else
#  define EXAMPLE1_MODULESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EXAMPLE1_MODULE_GLOBAL_H
